---
- name: Download installer script
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: ~{{ local_username }}/install-tailscale.sh
    mode: a+x

- name: Install tailscale
  script: ~{{ local_username }}/install-tailscale.sh

- name: Authorize machine
      ansible.builtin.command:
        argv:
          - 'tailscale'
          - 'up'
          - '--authkey'
          - "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"

...