---

- name: Download installer script
  get_url:
    url: https://tailscale.com/install.sh
    dest: ~{{ local_username }}/install-tailscale.sh
    mode: a+x

- name: Install tailscale
  script: ~{{ local_username }}/install-tailscale.sh

- name: Authorize machine
  command:
    argv:
      - 'tailscale'
      - 'up'
      - '--auth-key'
      - "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"

...