---
- name: Install tailscale
  script: https://tailscale.com/install.sh

- name: Authorize machine
      ansible.builtin.command:
        argv:
          - 'tailscale'
          - 'up'
          - '--authkey'
          - "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"

...