---

# - name: install libfuse
#   apt:
#     name: libfuse2
#     force_apt_get: true

# - name: create jetbrains toolbox directory
#   file:
#     path: "~{{ local_username }}/jetbrains-toolbox"
#     state: directory    
  
# - name: Download/unarchive Jetbrains Toolbox
#   unarchive:
#     src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.4.2.32922.tar.gz
#     dest: ~{{ local_username }}/jetbrains-toolbox
#     remote_src: yes
#     #creates: ~/jetbrains-toolbox-2.4.2.32922

# - name: Install JetBrains Toolbox
#   command: "~{{ local_username }}/jetbrains-toolbox/jetbrains-toolbox --install"

- name: Download jetbrains-toolbox.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh
    dest: ~{{ local_username }}/jetbrains-toolbox.sh
    mode: a+x

- name: Install Jetbrains Toolbox
  script: ~{{ local_username }}/jetbrains-toolbox.sh


...
